VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

LTO_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = custom

EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = spi_flash
